### ISSUE TITLE
Feature request: Txn.clone()

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#101]
### Description

I've got a loop that does a Transaction that does Test-and-set.  There's a lot of different things in the 'If' section, but only one of them is likely to change between loops (failure of the others is cause to exit the loop). 

### What I Did

```
success = False
while not success:
   cur_foo = self.client.range(foo).kvs[0].value
    t = Txn(self.cilent)
    t.compare(t.key(foo_bar).mod == 0)  # foo_bar doesn't exist
    t.compare(...)  # other conditions
    t.compare(t.key(foo) == cur_foo)  # make sure we're in the state we think we are
    t.success(t.put(foo, cur_foo + bar))
    t.fail(...) # consistent fail action
    t.commit()
    success = t.succeeded
```

### What I'd like to do

It'd be nice if there was a way to extract the common bits outside the loop, to make it run faster

```
base = Txn(self.client)
base.compare(base.key(foo_bar).mod == 0) # foo_bar doesn't exist
base.compare( .. ) # other conditions
base.fail(...) # consistent fail action
success = False
while not success:
    t = base.clone()
    t.compare(t.key(foo) == cur_foo)  # make sure we're in the state we think we are
    t.success(t.put(foo, cur_foo + bar))
    t.commit()
    success = t.succeeded
```

### Rationale

1.  It should be faster than having to reinitialize an entire new transaction each time, since the parts can be just copied over (as references, even!) and don't have to be constructed.
2. separating the static initialization from the dynamic

**Comment by Revolution1** [comment]
A `copy.deepcopy(txn)` will do the job.

**Comment by pjz** [comment]
Ah! Good to know!  Should I make you a PR with that trivial implementation? or should this issue just serve as documentation? :)

**Comment by pjz** [comment]
This actually fails for me with a (long) traceback that ends with:
```
  File "/tmp/venv/lib/python3.7/site-packages/etcd3/swagger_helper.py", line 211, in __getattribute__
    if key != 'spec' and key in self.spec:
  File "/tmp/venv/lib/python3.7/site-packages/etcd3/swagger_helper.py", line 220, in __getattribute__
    return super(SwaggerSpec, self).__getattribute__(key)
AttributeError: 'SwaggerSpec' object has no attribute 'spec'
```

So maybe a `.clone()` should be added just to keep it in tests :)

**Comment by pjz** [comment]
So I wrote it like this:
```
def TxnClone(src):
    return src.__class__(src.client, compare=list(src._compare), success=list(src._success), failure=list(src._failure)) 
```
which seems to work.

**Comment by Revolution1** [comment]
yeah
```
    def __copy__(self):
        return Txn(
            client=self.client,
            compare=copy.copy(self._compare),
            success=copy.copy(self._success),
            failure=copy.copy(self._failure)
        )
```
I wrote these code on my local disk, but i haven't got the time to test and release it
