### ISSUE TITLE
Unclosed client session

### ISSUE THREAD

**Issue by boylegu** [Revolution1/etcd3-py#116]
* etcd3-py version: 0.1.6
* Python version: 3.6.8
* Operating System: osx 10.13.6
* aiohttp: 3.6.2

### Description
First of all thank your solved my previous problem. But I seems meet new exception then. 
As follows:

### What I Did

```
from etcd3 import AioClient

client = AioClient('127.0.0.1', 2379)

async def AsyncFunc():
    await client.range("foo")

loop = asyncio.get_event_loop()
loop.run_until_complete(AsyncFunc())
```

===========
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x1089fa358>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x108956d48>, 349800.935111066)]']
connector: <aiohttp.connector.TCPConnector object at 0x1089fa320>
```

**Comment by Revolution1** [comment]
So far, you have to call `AioClient.close()` to manually close the session.

Not very straitforward, may improve that in the future.

And, the is more like a warning, not Exception.

**Comment by boylegu** [comment]
thanks a lot~
