### ISSUE TITLE
lease instance can not be awaited

### ISSUE THREAD

**Issue by Elune0syh** [Revolution1/etcd3-py#120]
I can`t do this

![image](https://user-images.githubusercontent.com/18223326/70606109-cceb3600-1c36-11ea-8beb-e2ac9972d55a.png)

It seems because 

![image](https://user-images.githubusercontent.com/18223326/70606275-12a7fe80-1c37-11ea-8563-af90891b426c.png)

**Comment by Revolution1** [comment]
yes, that is because current stateful utils does not support asyncio.
I will add async feature to them in the next minor version

**Comment by Revolution1** [comment]
For now, you can use low-level api instead.

**Comment by Elune0syh** [comment]
ok, Thanks
