### ISSUE TITLE
Add retries for HTTP calls

### ISSUE THREAD

**Issue by gszpura** [Revolution1/etcd3-py#31]
* etcd3-py version: master
* Python version: 2.7.13+

### Description

I cannot see any retries for HTTP calls.
It would be great to have retries somewhere here:

https://github.com/Revolution1/etcd3-py/blob/master/etcd3/client.py#L147

**Comment by Revolution1** [comment]
I think it's better to let users to handle http error themselves.

Besides, this lib is based on requests and aiohttp, they've already handled connection error retry well.

**Comment by Revolution1** [comment]
@gszpura check #32
