### ISSUE TITLE
Event() from Watcher does not expose etcd WatchResponse.header

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#78]
### Description

I'd like to see the global revision of a response to my Watch of a prefix.

### What I Did

Reading `stateful/watch.py'` shows that while the header is received, and the revision is even used for tracking, it's not attached to `Event`s that are dispatched.  

### What Should Happen

Just adding  a `.header` to the `Event` object and getting it set to the WatchResponse header would be great.

Alternately, if you wish to simplify things, an API closer to etcd's, that dispatches multiple events at a time (well, really passes them through directly from etcd) such that watching callbacks directly get a WatchResponse much like calls to `.range()` get a RangeResponse would also solve my issue.

**Comment by Revolution1** [comment]
@pjz  check this 

https://github.com/Revolution1/etcd3-py/blob/master/tests/test_watch_util.py#L177-L186

**Comment by pjz** [comment]
Looks good!  When's your next release?
