### ISSUE TITLE
Release? 0.1.5 is almost a year old now

### ISSUE THREAD

**Issue by pjz** [Revolution1/etcd3-py#86]
Any chance of a release soon? The current version on pypi is 10 months old.

**Comment by Revolution1** [comment]
Track my progress at https://github.com/Revolution1/etcd3-py/projects/1

> frankly, I'm quiet busy these days.

You can use `pip install https://github.com/Revolution1/etcd3-py/archive/master.zip` for the latest code.

If you want a release on pypi, is ok to publish a version on current master branch.
